import time
from threading import Event
import numpy as np
import sounddevice as sd
from kokoro import KModel, KPipeline
import config

class TTSManager:
    def __init__(self):
        self.model = None
        self.pipeline = None

    def load_model(self):
        """Instantiates Kokoro TTS network into memory."""
        self.model = KModel(repo_id="hexgrad/Kokoro-82M").to(config.DEVICE)
        self.pipeline = KPipeline(lang_code=config.KOKORO_LANG_CODE)

    def warm_up(self):
        """Runs a mock synthesis pass to eliminate initial latency."""
        assert self.pipeline is not None
        assert self.model is not None
        list(self.pipeline(config.KOKORO_WARMUP_WORD, voice=config.KOKORO_VOICE, model=self.model))

    def play_stream(self, text: str, stop_event: Event, shutdown_event: Event):
        """Streams audio frames generated by Kokoro directly to sounddevice in chunks."""
        assert self.pipeline is not None
        assert self.model is not None

        try:
            text = " ".join(text.split())
            if not text:
                return

            generator = self.pipeline(
                text,
                voice=config.KOKORO_VOICE,
                model=self.model,
            )

            with sd.OutputStream(
                    samplerate=config.KOKORO_SAMPLE_RATE,
                    channels=1,
                    dtype="float32",
                    blocksize=1024,
                    latency="low",
            ) as stream:

                for _, _, audio in generator:
                    if stop_event.is_set() or shutdown_event.is_set():
                        return

                    audio_chunk = np.asarray(audio, dtype=np.float32)
                    if audio_chunk.ndim == 1:
                        audio_chunk = audio_chunk.reshape(-1, 1)

                    stream.write(audio_chunk)

        except Exception as error:
            print(f"\nTTS Stream Play error: {error}")
			