from threading import Event
import numpy as np
import torch
import sounddevice as sd
from kokoro import KModel, KPipeline
import config


# Technical synthesizer & audio configurations
KOKORO_SAMPLE_RATE = 24_000   # Kokoro synthesizes native 24kHz audio outputs

# Language-specific warm-up words to prevent out-of-vocabulary phoneme warnings
KOKORO_WARMUP_WORDS = {
    "a": "Hi.",        # English (American)
    "b": "Hi.",        # English (British)
    "e": "Hola.",      # Spanish
    "f": "Salut.",     # French
    "g": "Hallo.",     # German
    "h": "नमस्ते",     # Hindi
    "i": "Ciao.",      # Italian
    "j": "こんにちは", # Japanese
    "p": "Olá.",       # Portuguese
    "r": "Привет.",    # Russian
    "z": "你好",       # Chinese
}
AUDIO_BLOCKSIZE = 1024
AUDIO_LATENCY = "low"
AUDIO_CHANNELS = 1
AUDIO_OUTPUT_DEVICE = None


class TTSManager:
    def __init__(self):
        self.model = None
        self.pipeline = None

    def load_model(self):
        """Instantiates Kokoro TTS network into memory."""
        self.model = KModel(repo_id="hexgrad/Kokoro-82M").to(config.DEVICE)
        self.pipeline = KPipeline(lang_code=config.KOKORO_LANG_CODE)

    def warm_up(self):
        """Runs a mock synthesis pass to eliminate initial latency."""
        assert self.pipeline is not None
        assert self.model is not None
        warmup_word = KOKORO_WARMUP_WORDS.get(config.KOKORO_LANG_CODE, "Hi.")
        list(self.pipeline(warmup_word, voice=config.KOKORO_VOICE, model=self.model))

    def play_stream(self, text: str, stop_event: Event, shutdown_event: Event):
        """Streams audio frames generated by Kokoro directly to sounddevice in chunks."""
        assert self.pipeline is not None
        assert self.model is not None

        try:
            text = " ".join(text.split())
            if not text:
                return

            generator = self.pipeline(
                text,
                voice=config.KOKORO_VOICE,
                model=self.model,
            )

            with sd.OutputStream(
                    samplerate=KOKORO_SAMPLE_RATE,
                    channels=AUDIO_CHANNELS,
                    dtype="float32",
                    blocksize=AUDIO_BLOCKSIZE,
                    latency=AUDIO_LATENCY,
                    device=AUDIO_OUTPUT_DEVICE,
            ) as stream:

                for _, _, audio in generator:
                    if stop_event.is_set() or shutdown_event.is_set():
                        return

                    audio_chunk = np.asarray(audio, dtype=np.float32)
                    if audio_chunk.ndim == 1:
                        audio_chunk = audio_chunk.reshape(-1, 1)

                    stream.write(audio_chunk)

        except Exception as error:
            print(f"\nTTS Stream Play error: {error}")
