import logging
from threading import Event, Lock
import numpy as np
import sounddevice as sd
from kokoro import KModel, KPipeline
import config
import io
import wave
import time

try:
    import winsound
    WINSOUND_AVAILABLE = True
except ImportError:
    WINSOUND_AVAILABLE = False

# Global thread-safety lock for PortAudio/sounddevice operations on Windows
sound_lock = Lock()


# Technical synthesizer & audio configurations
KOKORO_SAMPLE_RATE = 24_000   # Kokoro synthesizes native 24kHz audio outputs

# Silence padding prepended to every winsound playback block.
# Windows Audio Session needs ~50-200ms to initialize on the first call,
# which clips the very beginning of the first sentence without this buffer.
WINSOUND_LEAD_IN_SAMPLES = int(KOKORO_SAMPLE_RATE * 0.15)  # 150ms of silence

# Language-specific warm-up words to prevent out-of-vocabulary phoneme warnings
KOKORO_WARMUP_WORDS = {
    "a": "Hi.",        # English (American)
    "b": "Hi.",        # English (British)
    "e": "Hola.",      # Spanish
    "f": "Salut.",     # French
    "g": "Hallo.",     # German
    "h": "नमस्ते",     # Hindi
    "i": "Ciao.",      # Italian
    "j": "こんにちは", # Japanese
    "p": "Olá.",       # Portuguese
    "r": "Привет.",    # Russian
    "z": "你好",       # Chinese
}
PLAYBACK_BLOCKSIZE = 0      # 0 lets sounddevice choose optimal block size for output
AUDIO_LATENCY = None
AUDIO_CHANNELS = 1
AUDIO_OUTPUT_DEVICE = None


class TTSManager:
    def __init__(self):
        self.model = None
        self.pipeline = None

    def stop_playback(self):
        """Immediately interrupts any active winsound playback (Windows only)."""
        if WINSOUND_AVAILABLE:
            winsound.PlaySound(None, 0)

    def load_model(self):
        """Instantiates Kokoro TTS network into memory."""
        self.model = KModel(repo_id="hexgrad/Kokoro-82M").to(config.DEVICE)
        self.pipeline = KPipeline(lang_code=config.KOKORO_LANG_CODE)

    def warm_up(self):
        """Runs a mock synthesis pass to eliminate initial latency."""
        if self.model is None or self.pipeline is None:
            raise RuntimeError("TTS model not loaded. Call load_model() first.")
        warmup_word = KOKORO_WARMUP_WORDS.get(config.KOKORO_LANG_CODE, "Hi.")
        list(self.pipeline(warmup_word, voice=config.KOKORO_VOICE, model=self.model))

    def play_stream(self, text: str, stop_event: Event, shutdown_event: Event):
        """Streams audio frames generated by Kokoro directly to sounddevice in chunks."""
        if self.model is None or self.pipeline is None:
            raise RuntimeError("TTS model not loaded. Call load_model() first.")

        try:
            text = " ".join(text.split())
            if not text:
                return

            generator = self.pipeline(
                text,
                voice=config.KOKORO_VOICE,
                model=self.model,
            )

            # 1. Synthesize all audio chunks before opening the audio output stream.
            #    This avoids holding the stream open while the GPU is idle between chunks.
            audio_chunks = []
            for _, _, audio in generator:
                if stop_event.is_set() or shutdown_event.is_set():
                    return
                if audio is not None and len(audio) > 0:
                    audio_chunks.append(np.asarray(audio, dtype=np.float32))

            if not audio_chunks:
                return

            # Combine all synthesized chunks into a single array
            full_audio = np.concatenate(audio_chunks)

            # Windows-only robust winsound implementation (completely bypasses PortAudio MME error 6)
            if WINSOUND_AVAILABLE:
                # Normalise audio peak just in case to avoid clipping
                peak = np.max(np.abs(full_audio))
                if peak > 0:
                    full_audio = full_audio / peak * 0.9

                # Prepend silence so the Windows Audio Session has time to initialize
                # before real audio starts; prevents the first ~150ms from being clipped.
                lead_in = np.zeros(WINSOUND_LEAD_IN_SAMPLES, dtype=np.float32)
                full_audio = np.concatenate([lead_in, full_audio])

                # Convert float32 array (-1.0 to 1.0) to 16-bit PCM (-32768 to 32767)
                pcm_data = (full_audio * 32767).astype(np.int16)

                # Create an in-memory WAV byte stream
                wav_io = io.BytesIO()
                with wave.open(wav_io, 'wb') as wav_file:
                    wav_file.setnchannels(1)  # Mono
                    wav_file.setsampwidth(2)   # 16-bit PCM
                    wav_file.setframerate(KOKORO_SAMPLE_RATE)
                    wav_file.writeframes(pcm_data.tobytes())

                wav_bytes = wav_io.getvalue()

                # Play synchronously (we are in the background TTS thread).
                # Interruption is handled by stop_current_tts calling
                # winsound.PlaySound(None, 0) from the GUI thread, which
                # immediately aborts this blocking call.
                if stop_event.is_set() or shutdown_event.is_set():
                    return
                winsound.PlaySound(wav_bytes, winsound.SND_MEMORY | winsound.SND_NODEFAULT)

                return  # Playback completed successfully!

            # Fallback to sounddevice for non-Windows platforms
            if full_audio.ndim == 1:
                full_audio = full_audio.reshape(-1, 1)

            # 2. Open the audio output stream only when we are fully ready to play,
            # using sound_lock and a full PortAudio reset to heal any HDMI/NVIDIA driver disconnects
            # caused by CUDA power state transitions on Windows
            with sound_lock:
                try:
                    sd._terminate()
                    sd._initialize()
                except Exception as init_err:
                    logging.debug(f"PortAudio reinitialization error: {init_err}")

                stream = sd.OutputStream(
                        samplerate=KOKORO_SAMPLE_RATE,
                        channels=AUDIO_CHANNELS,
                        dtype="float32",
                        blocksize=PLAYBACK_BLOCKSIZE,
                        latency=AUDIO_LATENCY,
                        device=AUDIO_OUTPUT_DEVICE,
                )
                stream.start()

            try:
                # Write in smaller blocks to allow rapid stop_event checking during playback
                chunk_size = 1024
                for i in range(0, len(full_audio), chunk_size):
                    if stop_event.is_set() or shutdown_event.is_set():
                        return
                    chunk = full_audio[i:i+chunk_size]
                    stream.write(chunk)
            finally:
                with sound_lock:
                    try:
                        stream.stop()
                        stream.close()
                    except Exception as close_error:
                        logging.debug(f"Error during sound output stream close: {close_error}")

        except Exception as error:
            logging.error(f"TTS Stream Play error: {error}")
